spring:
  application:
    name: customer-info-app
  config:
    activate:
      on-profile:
    import: configserver:http://localhost:8888
server:
  servlet:
    context-path: /credit-status

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    health-check:
      enabled: true

experian:
  api-gateway:
    domain: http://localhost:8081
    endpoint:
      customerDetails: /experian/customerDetails

